dist: trusty
sudo: false
language: emacs-lisp
cache:
  - directories:
      # Cache stable Emacs binaries (saves 1min per job)
      - "$HOME/emacs/"
      - "$HOME/.roswell/"

env:
  - "TARGET=check-core        ROSWELL_LISP=sbcl-bin/1.2.14 EMACS_VERSION=24.4"
  - "TARGET=check-fancy       ROSWELL_LISP=sbcl-bin/1.2.14 EMACS_VERSION=24.4"
  - "TARGET=check-core        ROSWELL_LISP=sbcl-bin/1.2.14 EMACS_VERSION=25.2"
  - "TARGET=check-core        ROSWELL_LISP=ccl-bin         EMACS_VERSION=25.2"
  - "TARGET=check-fancy       ROSWELL_LISP=sbcl-bin/1.2.14 EMACS_VERSION=25.2"
  - "TARGET=check-fancy       ROSWELL_LISP=ccl-bin         EMACS_VERSION=25.2"
  - "TARGET=check-mrepl       ROSWELL_LISP=sbcl-bin/1.2.14 EMACS_VERSION=25.2"
  - "TARGET=check-indentation ROSWELL_LISP=sbcl-bin/1.2.14 EMACS_VERSION=25.2"

before_install:
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - make -f emacs-travis.mk install_emacs
  - export ROSWELL_INSTALL_DIR=~/.roswell && mkdir -p $ROSWELL_INSTALL_DIR
  - export PATH=$ROSWELL_INSTALL_DIR/bin:$PATH
  - export LISP=$ROSWELL_LISP
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - $ROSWELL_INSTALL_DIR/bin/ros use $ROSWELL_LISP
  - make LISP="ros run" EMACS=$HOME/emacs/$EMACS_VERSION/src/emacs $TARGET
